services:
  - type: web
    name: ticketing-app-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://aarnavsingh836@gmail.com:Cucumber@1729@rr.oldse8x.mongodb.net/user?retryWrites=true&w=majority&appName=rr"
    runtime: node
    region: oregon
